### PR TITLE
Pull Request of the third Microverse Project - NYT webpage

### PR DESCRIPTION
**Pull request by abouhid**
This pull request is for the code review of the third project which recreated the New York Times webpage. The coding includes HTML and CSS techniques such as:
- Grid tags;
- Flexbox ;
- Float positioning;

Thank you for your attention, hope to hear from you soon. Feedbacks are appreciated!

### CODE REVIEW

**Review by HADDADSOHAIB — CHANGES_REQUESTED** [review]
### Status: Change Required :recycle: 

### Hello @abouhid  and @Prabhakarzx   :hand: 

### Good job, you did great job with the project :+1: 

### Unfortunately, there are still some changes to get the project approved:
- The logo in the navbar should be a link.
- [x] The NY Times logo is a link ([link to page](https://www.nytimes.com/2014/03/18/science/space/detection-of-waves-in-space-buttresses-landmark-theory-of-big-bang.html?_r=0))
- The theory of inflation section has a scroll that does not exist in the original page.
your project:
Screenshot from 2020-06-20 00-37-55
Original
Screenshot from 2020-06-20 00-38-25
- The right part of the footer still need improvement. please make the most popular section like the original page.
your project:
Screenshot from 2020-06-20 00-39-43
Original
Screenshot from 2020-06-20 00-39-54

- [Optional] Use the nav tag in the navbar.
### Once you are done with the changes, ask for another code review. :1st_place_medal:

**Comment by Prabhakarzx** [comment]
**Dear @HADDADSOHAIB,**
We're glad to see your detailed review.
- Logo is now clickable along withe the left text
- We can't find the Scroll bar in our browser, @abouhid 's team also pointed out in the issue section but here there is no scroll bar showing to our chrome browser. and the property `overflow: hidden;` is applied. If you again find something, Do let us know how to fix it. Thanks!

NoSrollBar Showing

- Side right colum now have `margin-left: 30px;` 

**Thank You!**

**Review by tirthajyoti-ghosh — CHANGES_REQUESTED** [review]
# Status: Changes required 🚨

## Hello @abouhid and @Prabhakarzx 🖐. Impressive project team 🙌👏. Thanks for implementing the changes.

### But we need to work on some changes.

- The horizontal scrollbar is still showing.

image

On investigating, I found that you are using `iframe` to add this section to your clone. I would highly encourage you to make this section yourself, even though the original site is using it.

- The `editor's picks` section is overlapping with the fixed footer.

Annotation 2020-06-20 172124



Apply these changes and request another code review

Happy coding 👨‍💻

**Comment by Prabhakarzx** [comment]
**Dear @tirthajyoti-ghosh**,
Thank you for taking your time review the code!
Fixed the pointed out issues.
Thank You!

**Review by HADDADSOHAIB — APPROVED** [review]
### Status: Project Approved :+1:  

### Hello @abouhid  and @Prabhakarzx   :hand: 

### Good job, you did great job with the project :+1:, you implemented all changes so I approved the project.

### You can merge this branch into master.

**Comment by Prabhakarzx** [comment]
### Dear @HADDADSOHAIB and the TSE Team!

***We're thankful for all of the efforts and time you take to review our code. It makes us more confident in coding with the best practices.*** 
### Thank You so much! :bouquet:

**Pull request closed without merging**
